// Weekly report — executive commentary from the Brandzp BI agent.
//
// Feeds the BI agent a compact summary of the week's KPIs (Meta Ads,
// affiliates, Instagram, alerts) and asks for 3 insights + 3 prescribed
// actions. The output renders at the very top of the weekly PDF so the
// founder reads "what happened + what to do" before scrolling into the
// per-brand details.
//
// Why the BI agent (not Anthropic direct):
//   - The agent is domain-tuned for our analytics shape
//   - Future-proof: when the agent gets access to historical Brandzp data
//     it can frame insights ("this is the worst CPC since week 17") that
//     a stateless LLM can't
//
// Fallback: returns null (and the section just hides) if BI agent is
// unconfigured OR throws. Never blocks PDF generation.

import { askCreativeAgentJson, askBiAgentJson, isBiAgentConfigured } from "@/lib/clients/bi-agent-client";
import type { MetaAdsWeeklyReport } from "@/lib/services/meta-ads-report-service";
import type { AffiliateDeepDiveReport } from "@/lib/services/affiliate-deep-dive-service";
import type { RestockHeroAlertReport } from "@/lib/services/restock-hero-alert-service";
import type { RoasCollapseReport } from "@/lib/services/roas-collapse-service";

export interface BiWeeklyCommentary {
  // 1-sentence headline, e.g. "Strong ROAS week, but stockout risk on hero #2."
  headline: string;
  // 3 short insights (what the agent noticed in the data).
  insights: string[];
  // 3 prescribed actions for the founder this week.
  actions: string[];
  // Provenance so the UI can label "Generated by Brandzp BI agent at ...".
  agent: string;
  generatedAt: string;
}

export interface BiWeeklyCommentaryInput {
  storeName: string | null;
  periodStart: string;
  periodEnd: string;
  locale: "he" | "en";
  metaAds: MetaAdsWeeklyReport | null;
  affiliateDeepDive: AffiliateDeepDiveReport | null;
  restockAlerts: RestockHeroAlertReport | null;
  roasCollapseAlerts: RoasCollapseReport | null;
}

// Build a compact, structured digest the agent can reason over. We DON'T
// dump the entire bundle — most fields are redundant. We extract the
// "facts a smart human would pick out before writing the executive summary."
function buildDigest(input: BiWeeklyCommentaryInput): string {
  const lines: string[] = [];
  lines.push(`Store: ${input.storeName ?? "(unknown)"}`);
  lines.push(`Period: ${input.periodStart} → ${input.periodEnd}`);
  lines.push("");

  // ── Meta Ads totals + per-brand ROAS ──────────────────────────────
  if (input.metaAds) {
    const m = input.metaAds;
    const totals = m.brands.reduce(
      (acc, b) => ({
        spend: acc.spend + b.kpis.spend,
        purchases: acc.purchases + b.kpis.purchases,
        impressions: acc.impressions + b.kpis.impressions,
        clicks: acc.clicks + b.kpis.clicks,
        revenue: acc.revenue + (b.kpis.purchaseRoas != null ? b.kpis.spend * b.kpis.purchaseRoas : 0)
      }),
      { spend: 0, purchases: 0, impressions: 0, clicks: 0, revenue: 0 }
    );
    const totalRoas = totals.spend > 0 ? totals.revenue / totals.spend : null;
    lines.push("Meta Ads:");
    lines.push(`  Total spend: ₪${Math.round(totals.spend).toLocaleString()}`);
    lines.push(`  Total purchases (Meta-attributed): ${totals.purchases}`);
    lines.push(`  Weighted ROAS: ${totalRoas != null ? totalRoas.toFixed(2) + "×" : "n/a"}`);
    if (m.brands.length > 0) {
      lines.push("  By brand (ranked by spend):");
      const ranked = [...m.brands].sort((a, b) => b.kpis.spend - a.kpis.spend).slice(0, 5);
      for (const b of ranked) {
        const r = b.kpis.purchaseRoas;
        lines.push(
          `    - ${b.name}: ₪${Math.round(b.kpis.spend).toLocaleString()} spend, ROAS ${r != null ? r.toFixed(2) + "×" : "n/a"}, CTR ${(b.kpis.ctr * 100).toFixed(2)}%, ${b.kpis.purchases} purchases`
        );
      }
    }
    lines.push("");
  }

  // ── Affiliate deep-dive top 3 by sales ────────────────────────────
  if (input.affiliateDeepDive && input.affiliateDeepDive.affiliates.length > 0) {
    const aff = [...input.affiliateDeepDive.affiliates].sort((a, b) => b.sales - a.sales);
    lines.push("Affiliates (top by sales):");
    for (const a of aff.slice(0, 3)) {
      lines.push(`  - ${a.affiliateName || a.couponCode || a.affiliateMemberId}: ₪${Math.round(a.sales).toLocaleString()}, ${a.orders} orders`);
    }
    lines.push("");
  }

  // ── Red flags: restock + ROAS collapse ────────────────────────────
  if (input.restockAlerts && input.restockAlerts.flags.length > 0) {
    lines.push(`Restock alerts: ${input.restockAlerts.flags.length} hero products restocked this week (potential sales recovery).`);
    for (const f of input.restockAlerts.flags.slice(0, 3)) {
      lines.push(`  - ${f.title} (gap ${f.gapDays}d, prior revenue ₪${Math.round(f.priorRevenue).toLocaleString()})`);
    }
    lines.push("");
  }
  if (input.roasCollapseAlerts && input.roasCollapseAlerts.flags.length > 0) {
    lines.push(`ROAS collapse alerts: ${input.roasCollapseAlerts.flags.length} campaigns flagged.`);
    for (const c of input.roasCollapseAlerts.flags.slice(0, 3)) {
      lines.push(`  - ${c.campaignName} (${c.brandName}): ROAS ${c.roas.toFixed(2)}×, spend ₪${Math.round(c.spend).toLocaleString()}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function buildPrompt(input: BiWeeklyCommentaryInput, digest: string): string {
  const lang = input.locale === "he" ? "Hebrew" : "English";
  return [
    `You are the Brandzp BI agent writing the executive summary for this week's report.`,
    "",
    `Period: ${input.periodStart} → ${input.periodEnd}`,
    `Output language: ${lang}`,
    "",
    `DATA DIGEST:`,
    digest,
    "",
    `Write an executive summary in ${lang} that the founder will read in 60 seconds at the top of the PDF.`,
    `Be specific and concrete — cite numbers from the digest, not generalities.`,
    `Tone: confident, direct, no hedging, no "consider exploring" filler.`,
    "",
    `Output JSON object with these fields:`,
    `{`,
    `  "headline": "<one sentence, max 18 words, captures the week's main story>",`,
    `  "insights": ["<insight 1>", "<insight 2>", "<insight 3>"],`,
    `  "actions": ["<action 1>", "<action 2>", "<action 3>"]`,
    `}`,
    `Each insight: 1-2 sentences, what's interesting/concerning in the numbers.`,
    `Each action: 1 sentence, prescribed action with WHO does WHAT (e.g. "Scale '+ Advantage' adset budget by 30% Monday morning").`
  ].join("\n");
}

export async function generateWeeklyBiCommentary(input: BiWeeklyCommentaryInput): Promise<BiWeeklyCommentary | null> {
  if (!isBiAgentConfigured()) return null;
  const digest = buildDigest(input);
  if (digest.trim().length < 30) return null; // no data → no commentary

  try {
    // Prefer the BI analytics agent for this (it's an analytics task, not
    // a creative one). Falls back to the creative agent if BI returns
    // a bad shape — both can do JSON output via the same instruction.
    let parsed: { headline?: string; insights?: string[]; actions?: string[] };
    try {
      parsed = await askBiAgentJson<typeof parsed>({
        question: buildPrompt(input, digest),
        jsonHint: 'object with headline:string, insights:string[3], actions:string[3]',
        timeoutMs: 60_000
      });
    } catch {
      parsed = await askCreativeAgentJson<typeof parsed>({
        question: buildPrompt(input, digest),
        jsonHint: 'object with headline:string, insights:string[3], actions:string[3]',
        timeoutMs: 60_000
      });
    }

    const insights = Array.isArray(parsed.insights) ? parsed.insights.filter(Boolean).slice(0, 5) : [];
    const actions = Array.isArray(parsed.actions) ? parsed.actions.filter(Boolean).slice(0, 5) : [];
    const headline = (parsed.headline ?? "").trim();
    if (!headline && insights.length === 0 && actions.length === 0) return null;

    return {
      headline: headline || (input.locale === "he" ? "סיכום שבועי" : "Weekly executive summary"),
      insights,
      actions,
      agent: "brandzp-bi",
      generatedAt: new Date().toISOString()
    };
  } catch (err) {
    console.error("[weekly-bi-commentary] failed:", err);
    return null;
  }
}
