// This file is generated automatically by Next.js
// Do not edit this file manually

// Type definitions for Next.js routes

/**
 * Internal types used by the Next.js router and Link component.
 * These types are not meant to be used directly.
 * @internal
 */
declare namespace __next_route_internal_types__ {
  type SearchOrHash = `?${string}` | `#${string}`
  type WithProtocol = `${string}:${string}`

  type Suffix = '' | SearchOrHash

  type SafeSlug<S extends string> = S extends `${string}/${string}`
    ? never
    : S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type CatchAllSlug<S extends string> = S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type OptionalCatchAllSlug<S extends string> =
    S extends `${string}${SearchOrHash}` ? never : S

  type StaticRoutes = 
    | `/`
    | `/accept-invite`
    | `/affiliate-portal`
    | `/affiliate-portal/affiliates`
    | `/affiliate-portal/content`
    | `/affiliate-portal/conversions`
    | `/affiliate-portal/coupons`
    | `/affiliate-portal/payouts`
    | `/affiliate-portal/programs`
    | `/affiliate-portal/settings`
    | `/alerts`
    | `/api/affiliate-portal/affiliates`
    | `/api/affiliate-portal/affiliates/export`
    | `/api/affiliate-portal/affiliates/import`
    | `/api/affiliate-portal/bixgrow-import`
    | `/api/affiliate-portal/conversions/export`
    | `/api/affiliate-portal/conversions/import`
    | `/api/affiliate-portal/coupons/bulk`
    | `/api/affiliate-portal/coupons/create`
    | `/api/affiliate-portal/redirect`
    | `/api/affiliate-portal/sync-attribution`
    | `/api/auth/callback`
    | `/api/auth/signout`
    | `/api/billing/checkout`
    | `/api/billing/portal`
    | `/api/billing/webhook`
    | `/api/creative/jobs/worker`
    | `/api/creative/projects`
    | `/api/creative/prompt-preview`
    | `/api/creator/attribution/save`
    | `/api/creator/bixgrow/save`
    | `/api/creator/instagram/connect`
    | `/api/creator/instagram/oauth/callback`
    | `/api/creator/instagram/oauth/start`
    | `/api/creator/instagram/public-crawl`
    | `/api/creator/instagram/sync`
    | `/api/cron/backfill-order-attribution`
    | `/api/cron/measure-outcomes`
    | `/api/cron/refresh-all`
    | `/api/cron/shopify-sync`
    | `/api/cron/trial-ending-emails`
    | `/api/growth-agent/actions`
    | `/api/growth-agent/amazon-supplier-orders/drafts`
    | `/api/growth-agent/amazon-supplier-orders/mappings`
    | `/api/growth-agent/configuration`
    | `/api/growth-agent/connections`
    | `/api/growth-agent/findings`
    | `/api/growth-agent/health-check`
    | `/api/growth-agent/overview`
    | `/api/growth-agent/product-recommendations`
    | `/api/growth-agent/product-recommendations/import`
    | `/api/growth-agent/scan`
    | `/api/growth-agent/sync`
    | `/api/gsc/oauth/callback`
    | `/api/gsc/oauth/start`
    | `/api/marketing-planner/create-discount`
    | `/api/marketing-planner/data-readiness`
    | `/api/marketing-planner/generate`
    | `/api/meta-ads/connection/refresh`
    | `/api/meta-ads/connection/save`
    | `/api/meta-ads/connection/status`
    | `/api/meta-ads/sync`
    | `/api/meta/data-deletion`
    | `/api/meta/data-deletion/status`
    | `/api/products/costs`
    | `/api/products/costs/import`
    | `/api/reporting/refresh`
    | `/api/sales-summary/sync-products`
    | `/api/sales-summary/upload`
    | `/api/settings/account`
    | `/api/settings/active-store`
    | `/api/settings/bixgrow-slug`
    | `/api/settings/locale`
    | `/api/settings/organization`
    | `/api/settings/shopify-app-config`
    | `/api/settings/team/invite`
    | `/api/settings/team/member`
    | `/api/settings/team/revoke`
    | `/api/shopify/connection/save`
    | `/api/shopify/connection/test`
    | `/api/shopify/oauth/callback`
    | `/api/shopify/oauth/install`
    | `/api/shopify/sync/incremental`
    | `/api/shopify/sync/initial`
    | `/api/shopify/sync/status`
    | `/api/webhooks/shopify/orders`
    | `/api/weekly-summary/cron/run`
    | `/api/weekly-summary/export/meta-ads-pdf`
    | `/api/weekly-summary/recipients`
    | `/billing`
    | `/connect-brand`
    | `/creative`
    | `/creative/new`
    | `/creator-flow`
    | `/forgot-password`
    | `/growth-agent`
    | `/growth-agent/action-center`
    | `/growth-agent/configuration`
    | `/growth-agent/connections`
    | `/growth-agent/history`
    | `/growth-agent/rules`
    | `/growth-agent/supplier-orders`
    | `/marketing-planner`
    | `/print/meta-ads-weekly`
    | `/privacy`
    | `/product-follow-ups`
    | `/profit`
    | `/profit/costs`
    | `/reset-password`
    | `/retention`
    | `/sales-summary`
    | `/security`
    | `/settings`
    | `/settings/account`
    | `/settings/audit-log`
    | `/settings/organization`
    | `/signin`
    | `/signup`
    | `/terms`
    | `/trial-expired`
    | `/weekly-summary`
    | `/weekly-summary/history`
    | `/welcome`
  type DynamicRoutes<T extends string = string> = 
    | `/affiliate-portal/affiliates/${SafeSlug<T>}`
    | `/api/affiliate-portal/affiliates/${SafeSlug<T>}/instagram`
    | `/api/alerts/${SafeSlug<T>}/status`
    | `/api/creative/files/${CatchAllSlug<T>}`
    | `/api/creative/projects/${SafeSlug<T>}`
    | `/api/creative/projects/${SafeSlug<T>}/assets/${SafeSlug<T>}`
    | `/api/creative/projects/${SafeSlug<T>}/assets/${SafeSlug<T>}/publish`
    | `/api/creative/projects/${SafeSlug<T>}/assets/${SafeSlug<T>}/retry`
    | `/api/creative/projects/${SafeSlug<T>}/assets/${SafeSlug<T>}/video-edit`
    | `/api/creative/projects/${SafeSlug<T>}/export`
    | `/api/creative/projects/${SafeSlug<T>}/jobs`
    | `/api/growth-agent/actions/${SafeSlug<T>}/approve`
    | `/api/growth-agent/actions/${SafeSlug<T>}/reject`
    | `/api/growth-agent/amazon-supplier-orders/drafts/${SafeSlug<T>}/approve`
    | `/api/sales-summary/imports/${SafeSlug<T>}`
    | `/api/sales-summary/imports/${SafeSlug<T>}/export`
    | `/api/sales-summary/imports/${SafeSlug<T>}/export-pdf`
    | `/api/webhooks/bixgrow/${SafeSlug<T>}`
    | `/api/weekly-summary/history/${SafeSlug<T>}/pdf`
    | `/api/weekly-summary/recipients/${SafeSlug<T>}`
    | `/creative/${SafeSlug<T>}`
    | `/creative/${SafeSlug<T>}/edit-video/${SafeSlug<T>}`
    | `/creative/${SafeSlug<T>}/edit/${SafeSlug<T>}`
    | `/print/offline-status/${SafeSlug<T>}`

  type RouteImpl<T> = 
    | StaticRoutes
    | SearchOrHash
    | WithProtocol
    | `${StaticRoutes}${SearchOrHash}`
    | (T extends `${DynamicRoutes<infer _>}${Suffix}` ? T : never)
    
}

declare module 'next' {
  export { default } from 'next/types.js'
  export * from 'next/types.js'

  export type Route<T extends string = string> =
    __next_route_internal_types__.RouteImpl<T>
}

declare module 'next/link' {
  export { useLinkStatus } from 'next/dist/client/link.js'

  import type { LinkProps as OriginalLinkProps } from 'next/dist/client/link.js'
  import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
  import type { UrlObject } from 'url'

  type LinkRestProps = Omit<
    Omit<
      DetailedHTMLProps<
        AnchorHTMLAttributes<HTMLAnchorElement>,
        HTMLAnchorElement
      >,
      keyof OriginalLinkProps
    > &
      OriginalLinkProps,
    'href'
  >

  export type LinkProps<RouteInferType> = LinkRestProps & {
    /**
     * The path or URL to navigate to. This is the only required prop. It can also be an object.
     * @see https://nextjs.org/docs/api-reference/next/link
     */
    href: __next_route_internal_types__.RouteImpl<RouteInferType> | UrlObject
  }

  export default function Link<RouteType>(props: LinkProps<RouteType>): JSX.Element
}

declare module 'next/navigation' {
  export * from 'next/dist/client/components/navigation.js'

  import type { NavigateOptions, AppRouterInstance as OriginalAppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime.js'
  import type { RedirectType } from 'next/dist/client/components/redirect-error.js'
  
  interface AppRouterInstance extends OriginalAppRouterInstance {
    /**
     * Navigate to the provided href.
     * Pushes a new history entry.
     */
    push<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Navigate to the provided href.
     * Replaces the current history entry.
     */
    replace<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Prefetch the provided href.
     */
    prefetch<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>): void
  }

  export function useRouter(): AppRouterInstance;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 307/303 to the caller.
   * - In a Server Action, type defaults to 'push' and 'replace' elsewhere.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function redirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 308/303 to the caller.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function permanentRedirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
}

declare module 'next/form' {
  import type { FormProps as OriginalFormProps } from 'next/dist/client/form.js'

  type FormRestProps = Omit<OriginalFormProps, 'action'>

  export type FormProps<RouteInferType> = {
    /**
     * `action` can be either a `string` or a function.
     * - If `action` is a string, it will be interpreted as a path or URL to navigate to when the form is submitted.
     *   The path will be prefetched when the form becomes visible.
     * - If `action` is a function, it will be called when the form is submitted. See the [React docs](https://react.dev/reference/react-dom/components/form#props) for more.
     */
    action: __next_route_internal_types__.RouteImpl<RouteInferType> | ((formData: FormData) => void)
  } & FormRestProps

  export default function Form<RouteType>(props: FormProps<RouteType>): JSX.Element
}
