// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/(auth)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(paywall)/trial-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trial-expired">> = Specific
  const handler = {} as typeof import("../../app/(paywall)/trial-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/accept-invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accept-invite">> = Specific
  const handler = {} as typeof import("../../app/accept-invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/affiliates/[affiliateId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/affiliates/[affiliateId]">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/affiliates/[affiliateId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/affiliates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/affiliates">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/affiliates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/content">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/conversions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/conversions">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/conversions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/coupons">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/payouts">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/programs">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/affiliate-portal/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-portal/settings">> = Specific
  const handler = {} as typeof import("../../app/affiliate-portal/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../app/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/connect-brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connect-brand">> = Specific
  const handler = {} as typeof import("../../app/connect-brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative/[projectId]/edit-video/[assetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative/[projectId]/edit-video/[assetId]">> = Specific
  const handler = {} as typeof import("../../app/creative/[projectId]/edit-video/[assetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative/[projectId]/edit/[assetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative/[projectId]/edit/[assetId]">> = Specific
  const handler = {} as typeof import("../../app/creative/[projectId]/edit/[assetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/creative/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative/new">> = Specific
  const handler = {} as typeof import("../../app/creative/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative">> = Specific
  const handler = {} as typeof import("../../app/creative/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator-flow">> = Specific
  const handler = {} as typeof import("../../app/creator-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/action-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/action-center">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/action-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/configuration">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/connections">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/history">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/rules">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-agent/supplier-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-agent/supplier-orders">> = Specific
  const handler = {} as typeof import("../../app/growth-agent/supplier-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketing-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-planner">> = Specific
  const handler = {} as typeof import("../../app/marketing-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/print/meta-ads-weekly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/meta-ads-weekly">> = Specific
  const handler = {} as typeof import("../../app/print/meta-ads-weekly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/print/offline-status/[importId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/offline-status/[importId]">> = Specific
  const handler = {} as typeof import("../../app/print/offline-status/[importId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product-follow-ups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-follow-ups">> = Specific
  const handler = {} as typeof import("../../app/product-follow-ups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profit/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profit/costs">> = Specific
  const handler = {} as typeof import("../../app/profit/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profit">> = Specific
  const handler = {} as typeof import("../../app/profit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retention/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retention">> = Specific
  const handler = {} as typeof import("../../app/retention/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sales-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-summary">> = Specific
  const handler = {} as typeof import("../../app/sales-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account">> = Specific
  const handler = {} as typeof import("../../app/settings/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/audit-log">> = Specific
  const handler = {} as typeof import("../../app/settings/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/organization">> = Specific
  const handler = {} as typeof import("../../app/settings/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/weekly-summary/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weekly-summary/history">> = Specific
  const handler = {} as typeof import("../../app/weekly-summary/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/weekly-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weekly-summary">> = Specific
  const handler = {} as typeof import("../../app/weekly-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../app/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/affiliates/[affiliateId]/instagram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/affiliates/[affiliateId]/instagram">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/affiliates/[affiliateId]/instagram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/affiliates/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/affiliates/export">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/affiliates/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/affiliates/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/affiliates/import">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/affiliates/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/affiliates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/affiliates">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/affiliates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/bixgrow-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/bixgrow-import">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/bixgrow-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/conversions/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/conversions/export">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/conversions/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/conversions/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/conversions/import">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/conversions/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/coupons/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/coupons/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/coupons/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/coupons/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/coupons/create">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/coupons/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/redirect">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/affiliate-portal/sync-attribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate-portal/sync-attribution">> = Specific
  const handler = {} as typeof import("../../app/api/affiliate-portal/sync-attribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/alerts/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/alerts/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/files/[...key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/files/[...key]">> = Specific
  const handler = {} as typeof import("../../app/api/creative/files/[...key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/jobs/worker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/jobs/worker">> = Specific
  const handler = {} as typeof import("../../app/api/creative/jobs/worker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/assets/[assetId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/assets/[assetId]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/assets/[assetId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/assets/[assetId]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/assets/[assetId]/retry">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/assets/[assetId]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/assets/[assetId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/assets/[assetId]">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/assets/[assetId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/assets/[assetId]/video-edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/assets/[assetId]/video-edit">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/assets/[assetId]/video-edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/export">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/projects">> = Specific
  const handler = {} as typeof import("../../app/api/creative/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative/prompt-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/prompt-preview">> = Specific
  const handler = {} as typeof import("../../app/api/creative/prompt-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/attribution/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/attribution/save">> = Specific
  const handler = {} as typeof import("../../app/api/creator/attribution/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/bixgrow/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/bixgrow/save">> = Specific
  const handler = {} as typeof import("../../app/api/creator/bixgrow/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/instagram/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/instagram/connect">> = Specific
  const handler = {} as typeof import("../../app/api/creator/instagram/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/instagram/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/instagram/oauth/callback">> = Specific
  const handler = {} as typeof import("../../app/api/creator/instagram/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/instagram/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/instagram/oauth/start">> = Specific
  const handler = {} as typeof import("../../app/api/creator/instagram/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/instagram/public-crawl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/instagram/public-crawl">> = Specific
  const handler = {} as typeof import("../../app/api/creator/instagram/public-crawl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creator/instagram/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creator/instagram/sync">> = Specific
  const handler = {} as typeof import("../../app/api/creator/instagram/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/backfill-order-attribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/backfill-order-attribution">> = Specific
  const handler = {} as typeof import("../../app/api/cron/backfill-order-attribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/measure-outcomes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/measure-outcomes">> = Specific
  const handler = {} as typeof import("../../app/api/cron/measure-outcomes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/refresh-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/refresh-all">> = Specific
  const handler = {} as typeof import("../../app/api/cron/refresh-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/shopify-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/shopify-sync">> = Specific
  const handler = {} as typeof import("../../app/api/cron/shopify-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/trial-ending-emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/trial-ending-emails">> = Specific
  const handler = {} as typeof import("../../app/api/cron/trial-ending-emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/actions/[actionId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/actions/[actionId]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/actions/[actionId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/actions/[actionId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/actions/[actionId]/reject">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/actions/[actionId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/actions">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/amazon-supplier-orders/drafts/[draftId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/amazon-supplier-orders/drafts/[draftId]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/amazon-supplier-orders/drafts/[draftId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/amazon-supplier-orders/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/amazon-supplier-orders/drafts">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/amazon-supplier-orders/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/amazon-supplier-orders/mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/amazon-supplier-orders/mappings">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/amazon-supplier-orders/mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/configuration/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/configuration">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/configuration/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/connections">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/findings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/findings">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/findings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/health-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/health-check">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/health-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/overview">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/product-recommendations/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/product-recommendations/import">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/product-recommendations/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/product-recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/product-recommendations">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/product-recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/scan">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-agent/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-agent/sync">> = Specific
  const handler = {} as typeof import("../../app/api/growth-agent/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/oauth/callback">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/oauth/start">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketing-planner/create-discount/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-planner/create-discount">> = Specific
  const handler = {} as typeof import("../../app/api/marketing-planner/create-discount/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketing-planner/data-readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-planner/data-readiness">> = Specific
  const handler = {} as typeof import("../../app/api/marketing-planner/data-readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketing-planner/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-planner/generate">> = Specific
  const handler = {} as typeof import("../../app/api/marketing-planner/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-ads/connection/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-ads/connection/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/meta-ads/connection/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-ads/connection/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-ads/connection/save">> = Specific
  const handler = {} as typeof import("../../app/api/meta-ads/connection/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-ads/connection/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-ads/connection/status">> = Specific
  const handler = {} as typeof import("../../app/api/meta-ads/connection/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-ads/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-ads/sync">> = Specific
  const handler = {} as typeof import("../../app/api/meta-ads/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta/data-deletion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/data-deletion">> = Specific
  const handler = {} as typeof import("../../app/api/meta/data-deletion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta/data-deletion/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/data-deletion/status">> = Specific
  const handler = {} as typeof import("../../app/api/meta/data-deletion/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/costs/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/costs/import">> = Specific
  const handler = {} as typeof import("../../app/api/products/costs/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/costs">> = Specific
  const handler = {} as typeof import("../../app/api/products/costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reporting/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reporting/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/reporting/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sales-summary/imports/[importId]/export-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary/imports/[importId]/export-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/sales-summary/imports/[importId]/export-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sales-summary/imports/[importId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary/imports/[importId]/export">> = Specific
  const handler = {} as typeof import("../../app/api/sales-summary/imports/[importId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sales-summary/imports/[importId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary/imports/[importId]">> = Specific
  const handler = {} as typeof import("../../app/api/sales-summary/imports/[importId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sales-summary/sync-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary/sync-products">> = Specific
  const handler = {} as typeof import("../../app/api/sales-summary/sync-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sales-summary/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary/upload">> = Specific
  const handler = {} as typeof import("../../app/api/sales-summary/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/account">> = Specific
  const handler = {} as typeof import("../../app/api/settings/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/active-store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/active-store">> = Specific
  const handler = {} as typeof import("../../app/api/settings/active-store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/bixgrow-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/bixgrow-slug">> = Specific
  const handler = {} as typeof import("../../app/api/settings/bixgrow-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/locale">> = Specific
  const handler = {} as typeof import("../../app/api/settings/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/organization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/organization">> = Specific
  const handler = {} as typeof import("../../app/api/settings/organization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/shopify-app-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/shopify-app-config">> = Specific
  const handler = {} as typeof import("../../app/api/settings/shopify-app-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/team/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/team/invite">> = Specific
  const handler = {} as typeof import("../../app/api/settings/team/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/team/member/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/team/member">> = Specific
  const handler = {} as typeof import("../../app/api/settings/team/member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/team/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/team/revoke">> = Specific
  const handler = {} as typeof import("../../app/api/settings/team/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/connection/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/connection/save">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/connection/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/connection/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/connection/test">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/connection/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/oauth/callback">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/oauth/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/oauth/install">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/oauth/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/sync/incremental/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/sync/incremental">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/sync/incremental/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/sync/initial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/sync/initial">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/sync/initial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/sync/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/sync/status">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/sync/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/bixgrow/[storeSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/bixgrow/[storeSlug]">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/bixgrow/[storeSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/shopify/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/shopify/orders">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/shopify/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-summary/cron/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-summary/cron/run">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-summary/cron/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-summary/export/meta-ads-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-summary/export/meta-ads-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-summary/export/meta-ads-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-summary/history/[reportId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-summary/history/[reportId]/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-summary/history/[reportId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-summary/recipients/[recipientId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-summary/recipients/[recipientId]">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-summary/recipients/[recipientId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-summary/recipients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-summary/recipients">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-summary/recipients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
